POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Juan Valdomero",
    "number": 234234234
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "ffffff",
    "number": 23423454112
}